version: '3.4'

services:
  tot800:
    container_name: tot800
    image: tot800
    entrypoint: /home/tot800/entrypoint.sh
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/tot800
      - ./pip_cache:/root/.cache/pip
