version: '3.4'

services:
  tot800:
    container_name: $APP_NAME
    image: ${APP_NAME}-app
    entrypoint: /home/$APP_NAME/app/entrypoint.sh
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/$APP_NAME/app
      - ./app_cache:/home/$APP_NAME/.cache
