version: '3.4'

services:
  tot800:
    container_name: tot800
    image: tot800
    entrypoint: /home/tot800/entrypoint.sh
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/tot800
